# Generated by Django 5.2.17 on 2026-09-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_city_lat_city_lon_city_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='city',
            name='lon',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='city',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
