# Generated by Django 5.2.17 on 2026-10-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='lat',
            field=models.FloatField(default=54.5),
        ),
        migrations.AddField(
            model_name='city',
            name='lon',
            field=models.FloatField(default=54.5),
        ),
        migrations.AddField(
            model_name='city',
            name='title',
            field=models.CharField(default='tehran', max_length=50),
        ),
    ]
